# Generated by Django 5.1.3 on 2024-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
