# Generated by Django 5.1.3 on 2024-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gmail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
