# Generated by Django 5.1.3 on 2024-11-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_gmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='gmail',
            new_name='email',
        ),
    ]
